// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkFeHEL0xPZmKAhovJVLZab0IHmcdYjtU',
    appId: '1:553636514825:web:552793490753b97848bcd8',
    messagingSenderId: '553636514825',
    projectId: 'enduring-tea-306116',
    authDomain: 'enduring-tea-306116.firebaseapp.com',
    storageBucket: 'enduring-tea-306116.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvAxi0415kZmRoK1dP0liJKF0iu9eZuow',
    appId: '1:553636514825:android:f7eb8d9fa3b57ee448bcd8',
    messagingSenderId: '553636514825',
    projectId: 'enduring-tea-306116',
    storageBucket: 'enduring-tea-306116.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1X4jqoqb3lLgXkxdWEQQCNtCsM4s5LnI',
    appId: '1:553636514825:ios:d94df77e49c10f5748bcd8',
    messagingSenderId: '553636514825',
    projectId: 'enduring-tea-306116',
    storageBucket: 'enduring-tea-306116.appspot.com',
    iosBundleId: 'com.example.diplom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1X4jqoqb3lLgXkxdWEQQCNtCsM4s5LnI',
    appId: '1:553636514825:ios:4f3246f9c11c48d248bcd8',
    messagingSenderId: '553636514825',
    projectId: 'enduring-tea-306116',
    storageBucket: 'enduring-tea-306116.appspot.com',
    iosBundleId: 'com.example.diplom.RunnerTests',
  );
}
